{
    "name": "Ahadu HR Management",
    "version": "18.0.1.0.0",
    "category": "Human Resources",
    "summary": "HR Employee Management System",
    "author": "Ahadu Bank DevTeam",
    "license": "Other proprietary",
    "website": "https://www.ahadubank.com",
    "depends": [
        "hr",
        "base",
        "hr_holidays",
        "mail",
        "resource",
        "account",
        "hr_skills",
    ],
    "data": [
        "wizard/hr_approval_reject_wizard_views.xml",
        "wizard/hr_employee_reassign_wizard_views.xml",
        "views/res_config_settings_views.xml",
        "views/ahadu_fuel_price_views.xml",
        "security/ir.model.access.csv",
        "security/hr_approval_security.xml",
        "data/hr_notification_data.xml",
        "data/hr_employee_type_data.xml",
        # "data/hr_organogram_data.xml",
        # "data/hr_probation_data.xml",
        # "data/hr_approval_policy_data.xml",
        "views/hr_grade_views.xml",
        "views/hr_region_views.xml",
        "views/hr_city_views.xml",
        "views/hr_cost_center_views.xml",
        "views/hr_configuration_views.xml",
        "views/hr_hardship_allowance_views.xml",
        "views/hr_approval_policy_views.xml",
        "views/hr_employee_probation_views.xml",
        "views/hr_job_views.xml",
        "views/hr_department_views.xml",
        "views/hr_benefit_package_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_employee_ctc_views.xml",
        # "views/hr_resume_views.xml",
        "views/hr_employee_experience_views.xml",
        "views/hr_employee_activity_views.xml",
        "views/hr_employee_promotion_views.xml",
        "views/hr_employee_transfer_views.xml",
        "views/hr_employee_type_views.xml",
        "views/hr_employee_demotion_views.xml",
        "views/hr_employee_disciplinary_views.xml",
        "views/hr_employee_guarantee_views.xml",
        "views/hr_employee_termination_views.xml",
        "views/hr_employee_acting_views.xml",
        "views/hr_employee_temporary_assignment_views.xml",
        'views/hr_employee_retirement_views.xml', # Make sure this is here
        'views/hr_additional_activity_views.xml',
        "views/hr_organization_chart_views.xml",
        "views/hr_report_views.xml",
        "views/hr_analytics_dashboard_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_organogram_node_views.xml",
        "views/hr_structural_org_chart_views.xml",
        "views/menu_items.xml",
    ],
    "assets": {
        "web.assets_backend": [
            # "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js",
            "ahadu_hr/static/src/lib/chart.umd.js",
            "ahadu_hr/static/src/css/ahadu_hr.css",
            "ahadu_hr/static/src/css/hr_reporting_dashboard.css",
            "ahadu_hr/static/src/css/hr_organization_chart.css",
            "ahadu_hr/static/src/css/structural_org_chart.css",
            "ahadu_hr/static/src/css/hr_analytics_dashboard.css",
            "ahadu_hr/static/src/js/dashboard.js",
            "ahadu_hr/static/src/js/hr_reporting_dashboard.js",
            "ahadu_hr/static/src/js/hr_organization_chart.js",
            "ahadu_hr/static/src/js/structural_org_chart.js",
            "ahadu_hr/static/src/js/hr_analytics_dashboard.js",
            "ahadu_hr/static/src/xml/hr_reporting_dashboard.xml",
            "ahadu_hr/static/src/xml/hr_organization_chart.xml",
            "ahadu_hr/static/src/xml/structural_org_chart.xml",
            "ahadu_hr/static/src/xml/hr_analytics_dashboard.xml",
        ],
    },
    "installable": True,
    "auto_install": False,
    "application": True,
}
