# -*- coding: utf-8 -*-
from . import ahadu_account
from . import ahadu_journal_entry
from . import ahadu_pay_group
from . import ahadu_payroll_region
from . import hr_contract
from . import hr_employee
from . import hr_employee_deduction
from . import hr_payslip
from . import hr_payslip_run
from . import hr_salary_rule
from . import hr_termination_payslip
from . import hr_termination_run
from . import res_config_settings
from . import res_users
from . import ahadu_overtime
from . import ahadu_tax_config
from . import ahadu_payroll_report_wizard
from . import comparative_analytics
from . import hr_branch_mapping
from . import cash_indemnity_models
from . import hr_employee_bank_account
from . import payroll_dashboard
from . import hr_loan_type
from . import hr_loan
