# -*- coding: utf-8 -*-
import io
import csv
import base64
from odoo import models, fields, api, _
from odoo.exceptions import UserError, ValidationError
import datetime

# Ensure xlsxwriter is imported cleanly
try:
    import xlsxwriter
except ImportError:
    xlsxwriter = None

class ProjectReportWizard(models.TransientModel):
    _name = 'project.report.wizard'
    _description = 'Project Management System Report Generator'

    REPORT_TYPE_SELECTION = [
        ('executive', 'Executive Management Report (CEO/CIO)'),
        ('sponsor', 'Project Sponsor Report'),
        ('pmo', 'IT Program Management & Innovation Department (PMO) Report'),
        ('division', 'Enterprise Program & Architecture Division Report'),
        ('pm', 'Project Manager Report'),
        ('team', 'Project Team Member Report'),
    ]

    report_type = fields.Selection(
        REPORT_TYPE_SELECTION,
        string="Report Type",
        required=True,
        default='executive'
    )
    date_from = fields.Date(
        string="Start Date",
        default=lambda self: datetime.date.today().replace(month=1, day=1)
    )
    date_to = fields.Date(
        string="End Date",
        default=fields.Date.today
    )
    project_ids = fields.Many2many(
        'project.project',
        string="Projects Filter",
        help="Select projects to include in the report. If empty, all authorized projects in the scope will be included."
    )
    export_format = fields.Selection([
        ('xlsx', 'Excel (.xlsx)'),
        ('pdf', 'PDF Document'),
        ('csv', 'CSV Text')
    ], string="Export Format", required=True, default='xlsx')

    # Security check dynamic restriction
    @api.onchange('report_type')
    def _onchange_report_type_access(self):
        roles = self.env['project.dashboard.access'].get_authorized_dashboard_roles()
        if self.report_type and self.report_type not in roles:
            # Inform user in view/onchange or raise validation later
            pass

    def _get_authorized_projects(self):
        """Filters project records according to the selected report type's business rules."""
        roles = self.env['project.dashboard.access'].get_authorized_dashboard_roles()
        if self.report_type not in roles:
            raise UserError(_("Access Denied: Your current job position is not authorized to generate the %s.") % 
                            dict(self._fields['report_type'].selection).get(self.report_type))

        domain = [('create_date', '>=', fields.Datetime.to_string(self.date_from)),
                  ('create_date', '<=', fields.Datetime.to_string(self.date_to))]

        if self.report_type == 'sponsor':
            employee = self.env['hr.employee'].sudo().search([('user_id', '=', self.env.user.id)], limit=1)
            if employee:
                domain.append(('project_sponsor_id', '=', employee.id))
            else:
                domain.append(('project_sponsor_id', '=', False))
        elif self.report_type == 'pm':
            domain.append(('user_id', '=', self.env.user.id))
        elif self.report_type == 'team':
            # Project team member sees projects where they are assigned to at least one task
            domain.append(('task_ids.user_ids', 'in', [self.env.user.id]))

        projects = self.env['project.project'].search(domain)
        if self.project_ids:
            projects = projects.filtered(lambda p: p.id in self.project_ids.ids)
        
        return projects

    def generate_report(self):
        self.ensure_one()
        # Enforce security validation check
        projects = self._get_authorized_projects()
        if not projects:
            raise UserError(_("No authorized projects found in the selected date range."))

        if self.export_format == 'xlsx':
            return self._export_xlsx(projects)
        elif self.export_format == 'pdf':
            return self._export_pdf(projects)
        elif self.export_format == 'csv':
            return self._export_csv(projects)

    def _export_csv(self, projects):
        output = io.StringIO()
        writer = csv.writer(output, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        
        # Simple flat CSV format representing overall project summary
        writer.writerow(["Report Title", dict(self._fields['report_type'].selection).get(self.report_type)])
        writer.writerow(["Reporting Period", "%s to %s" % (self.date_from, self.date_to)])
        writer.writerow(["Generated By", self.env.user.name])
        writer.writerow([])
        
        writer.writerow(["Project Code", "Project Name", "Sponsor", "Directorate", "PM", "Progress (%)", "Budget", "Actual Cost", "Variance", "Health", "Status"])
        for p in projects:
            writer.writerow([
                p.project_code,
                p.name,
                p.project_sponsor_id.name or '',
                p.project_department_id.name or '',
                p.user_id.name or '',
                p.project_progress,
                p.budget_amount,
                p.actual_cost,
                p.budget_variance,
                dict(p._fields['project_health'].selection).get(p.project_health, p.project_health) if p.project_health else '',
                dict(p._fields['state'].selection).get(p.state, p.state) if p.state else ''
            ])
            
        csv_data = base64.b64encode(output.getvalue().encode('utf-8'))
        attachment = self.env['ir.attachment'].create({
            'name': 'Project_Report_%s.csv' % self.report_type,
            'type': 'binary',
            'datas': csv_data,
            'store_fname': 'Project_Report_%s.csv' % self.report_type,
            'mimetype': 'text/csv'
        })
        return {
            'type': 'ir.actions.act_url',
            'url': '/web/content/%s?download=true' % attachment.id,
            'target': 'new',
        }

    def _export_xlsx(self, projects):
        if not xlsxwriter:
            raise UserError(_("Python 'xlsxwriter' library is not installed on this system."))

        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output, {'in_memory': True})
        
        # Styles
        title_format = workbook.add_format({'bold': True, 'font_size': 16, 'align': 'center', 'valign': 'vcenter', 'font_color': '#1f4e78'})
        header_format = workbook.add_format({'bold': True, 'bg_color': '#2f5597', 'font_color': '#ffffff', 'border': 1, 'align': 'center', 'valign': 'vcenter'})
        section_format = workbook.add_format({'bold': True, 'bg_color': '#d9e1f2', 'border': 1, 'font_size': 11})
        data_format = workbook.add_format({'border': 1, 'align': 'left', 'valign': 'vcenter'})
        num_format = workbook.add_format({'border': 1, 'num_format': '#,##0.00', 'align': 'right'})
        pct_format = workbook.add_format({'border': 1, 'num_format': '0.0%', 'align': 'center'})
        footer_format = workbook.add_format({'font_size': 9, 'italic': True, 'align': 'left'})

        # Retrieve classifications and classification terms
        classification = "Confidential - Ahadu Bank Internal"
        system_name = "Ahadu Project Management System"
        owner_name = "Enterprise PMO"
        timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        # ----------------------------------------------------
        # 1. Executive Management Report
        # ----------------------------------------------------
        if self.report_type == 'executive':
            sheet = workbook.add_worksheet('Executive Summary')
            sheet.set_column('A:H', 18)

            # Metadata Header Rows
            sheet.merge_range('A2:H2', 'AHADU BANK S.C.', title_format)
            sheet.merge_range('A3:H3', 'EXECUTIVE PORTFOLIO PERFORMANCE REPORT', workbook.add_format({'bold': True, 'font_size': 12, 'align': 'center'}))
            sheet.write('A5', 'Reporting Period:')
            sheet.write('B5', '%s to %s' % (self.date_from, self.date_to))
            sheet.write('A6', 'Generated By:')
            sheet.write('B6', self.env.user.name)
            sheet.write('E5', 'Report Date:')
            sheet.write('F5', datetime.date.today().strftime('%Y-%m-%d'))
            sheet.write('E6', 'Generated On:')
            sheet.write('F6', timestamp)

            row = 8
            # Section: Portfolio Summary
            sheet.merge_range(row, 0, row, 7, '1. Portfolio Summary', section_format)
            row += 1
            headers = ['Project Code', 'Project Name', 'Sponsor', 'Directorate', 'PM', 'Progress (%)', 'Budget', 'Health', 'Status']
            for col_idx, h in enumerate(headers):
                sheet.write(row, col_idx, h, header_format)
            row += 1
            
            for p in projects:
                sheet.write(row, 0, p.project_code, data_format)
                sheet.write(row, 1, p.name, data_format)
                sheet.write(row, 2, p.project_sponsor_id.name or '', data_format)
                sheet.write(row, 3, p.project_department_id.name or '', data_format)
                sheet.write(row, 4, p.user_id.name or '', data_format)
                sheet.write(row, 5, p.project_progress / 100.0, pct_format)
                sheet.write(row, 6, p.budget_amount, num_format)
                sheet.write(row, 7, dict(p._fields['project_health'].selection).get(p.project_health, p.project_health) if p.project_health else '', data_format)
                row += 1

            row += 2
            # Section: Budget Summary
            sheet.merge_range(row, 0, row, 7, '2. Budget Summary & Variance Analysis', section_format)
            row += 1
            headers_budget = ['Project Code', 'Project Name', 'Planned Budget', 'Actual Expenditure', 'Variance', 'Utilization Rate (%)', 'Budget Status', 'Health']
            for col_idx, h in enumerate(headers_budget):
                sheet.write(row, col_idx, h, header_format)
            row += 1
            for p in projects:
                util_rate = (p.actual_cost / p.budget_amount) if p.budget_amount > 0 else 0.0
                sheet.write(row, 0, p.project_code, data_format)
                sheet.write(row, 1, p.name, data_format)
                sheet.write(row, 2, p.budget_amount, num_format)
                sheet.write(row, 3, p.actual_cost, num_format)
                sheet.write(row, 4, p.budget_variance, num_format)
                sheet.write(row, 5, util_rate, pct_format)
                sheet.write(row, 6, dict(p._fields['budget_status'].selection).get(p.budget_status, p.budget_status) if p.budget_status else '', data_format)
                sheet.write(row, 7, dict(p._fields['project_health'].selection).get(p.project_health, p.project_health) if p.project_health else '', data_format)
                row += 1

            row += 2
            # Section: Risk & Issues Summary
            sheet.merge_range(row, 0, row, 7, '3. Critical Risks & Issues Register', section_format)
            row += 1
            headers_risk = ['Project Name', 'Open Risks Count', 'Critical Issues Count', 'Delayed Status', 'Pending Approvals', 'Health', '', '']
            sheet.merge_range(row, 0, row, 2, 'Project Description', header_format)
            sheet.write(row, 3, 'Open Risks', header_format)
            sheet.write(row, 4, 'Critical Issues', header_format)
            sheet.write(row, 5, 'Is Delayed', header_format)
            sheet.write(row, 6, 'Project Health', header_format)
            sheet.write(row, 7, 'Status', header_format)
            row += 1
            for p in projects:
                sheet.merge_range(row, 0, row, 2, p.name, data_format)
                sheet.write(row, 3, p.open_risks_count, data_format)
                sheet.write(row, 4, p.critical_issues_count, data_format)
                sheet.write(row, 5, 'Yes' if p.is_delayed else 'No', data_format)
                sheet.write(row, 6, dict(p._fields['project_health'].selection).get(p.project_health, p.project_health) if p.project_health else '', data_format)
                sheet.write(row, 7, dict(p._fields['state'].selection).get(p.state, p.state) if p.state else '', data_format)
                row += 1

            # Footer
            row += 3
            sheet.write(row, 0, 'System: %s' % system_name, footer_format)
            sheet.write(row, 2, 'Timestamp: %s' % timestamp, footer_format)
            sheet.write(row, 4, 'Owner: %s' % owner_name, footer_format)
            sheet.write(row, 6, 'Classification: %s' % classification, footer_format)

        # ----------------------------------------------------
        # 2. Project Sponsor Report
        # ----------------------------------------------------
        elif self.report_type == 'sponsor':
            sheet = workbook.add_worksheet('Sponsor Dashboard')
            sheet.set_column('A:F', 20)

            sheet.merge_range('A2:F2', 'AHADU BANK S.C.', title_format)
            sheet.merge_range('A3:F3', 'PROJECT SPONSOR OVERSIGHT REPORT', workbook.add_format({'bold': True, 'font_size': 12, 'align': 'center'}))
            sheet.write('A5', 'Sponsor Name:')
            sheet.write('B5', self.env.user.name)
            sheet.write('D5', 'Report Date:')
            sheet.write('E5', datetime.date.today().strftime('%Y-%m-%d'))

            row = 7
            sheet.merge_range(row, 0, row, 5, 'Sponsored Projects Portfolio', section_format)
            row += 1
            headers = ['Project Name', 'Project Manager', 'Progress (%)', 'Budget', 'Health', 'Status']
            for col_idx, h in enumerate(headers):
                sheet.write(row, col_idx, h, header_format)
            row += 1
            for p in projects:
                sheet.write(row, 0, p.name, data_format)
                sheet.write(row, 1, p.user_id.name or '', data_format)
                sheet.write(row, 2, p.project_progress / 100.0, pct_format)
                sheet.write(row, 3, p.budget_amount, num_format)
                sheet.write(row, 4, dict(p._fields['project_health'].selection).get(p.project_health, p.project_health) if p.project_health else '', data_format)
                sheet.write(row, 5, dict(p._fields['state'].selection).get(p.state, p.state) if p.state else '', data_format)
                row += 1

            row += 2
            sheet.merge_range(row, 0, row, 5, 'Critical Actions & Approvals Required', section_format)
            row += 1
            sheet.write(row, 0, 'Project', header_format)
            sheet.merge_range(row, 1, row, 2, 'Pending Approvals Item', header_format)
            sheet.write(row, 3, 'Overdue Tasks', header_format)
            sheet.write(row, 4, 'Change Requests', header_format)
            sheet.write(row, 5, 'Health Status', header_format)
            row += 1
            for p in projects:
                # Calculate pending change requests count
                pending_crs = len(p.change_request_ids.filtered(lambda c: c.state == 'reviewed'))
                sheet.write(row, 0, p.name, data_format)
                sheet.merge_range(row, 1, row, 2, 'Sponsor Action Item' if pending_crs > 0 else 'None', data_format)
                sheet.write(row, 3, p.overdue_tasks_count, data_format)
                sheet.write(row, 4, pending_crs, data_format)
                sheet.write(row, 5, dict(p._fields['project_health'].selection).get(p.project_health, p.project_health) if p.project_health else '', data_format)
                row += 1

            row += 3
            sheet.write(row, 0, 'System: %s' % system_name, footer_format)
            sheet.write(row, 2, 'Classification: %s' % classification, footer_format)

        # ----------------------------------------------------
        # 3. IT PMO Directorate Report
        # ----------------------------------------------------
        elif self.report_type == 'pmo':
            sheet = workbook.add_worksheet('PMO Portfolio Report')
            sheet.set_column('A:G', 18)

            sheet.merge_range('A2:G2', 'AHADU BANK S.C.', title_format)
            sheet.merge_range('A3:G3', 'IT PROGRAM MANAGEMENT & INNOVATION PORTFOLIO KPI REPORT', workbook.add_format({'bold': True, 'font_size': 11, 'align': 'center'}))
            
            row = 6
            sheet.merge_range(row, 0, row, 6, 'Portfolio Performance Metrics by Directorate / Division', section_format)
            row += 1
            headers = ['Project Name', 'Division', 'Sponsor', 'Project Manager', 'Progress (%)', 'Budget Amount', 'Health']
            for col_idx, h in enumerate(headers):
                sheet.write(row, col_idx, h, header_format)
            row += 1
            for p in projects:
                sheet.write(row, 0, p.name, data_format)
                sheet.write(row, 1, p.project_division_id.name or '', data_format)
                sheet.write(row, 2, p.project_sponsor_id.name or '', data_format)
                sheet.write(row, 3, p.user_id.name or '', data_format)
                sheet.write(row, 4, p.project_progress / 100.0, pct_format)
                sheet.write(row, 5, p.budget_amount, num_format)
                sheet.write(row, 6, dict(p._fields['project_health'].selection).get(p.project_health, p.project_health) if p.project_health else '', data_format)
                row += 1

            row += 3
            sheet.write(row, 0, 'System: %s' % system_name, footer_format)
            sheet.write(row, 3, 'Classification: %s' % classification, footer_format)

        # ----------------------------------------------------
        # 4. EPAD Division Report
        # ----------------------------------------------------
        elif self.report_type == 'division':
            sheet = workbook.add_worksheet('EPAD Execution Summary')
            sheet.set_column('A:H', 18)

            sheet.merge_range('A2:H2', 'AHADU BANK S.C.', title_format)
            sheet.merge_range('A3:H3', 'ENTERPRISE PROGRAM & ARCHITECTURE DIVISION EXECUTION REPORT', workbook.add_format({'bold': True, 'font_size': 11, 'align': 'center'}))

            row = 6
            sheet.merge_range(row, 0, row, 7, 'Project Execution & Resource Summary', section_format)
            row += 1
            headers = ['Project Code', 'Project Name', 'Project Manager', 'WBS Phases Count', 'Milestones Reached', 'Overdue Tasks', 'Budget', 'Health']
            for col_idx, h in enumerate(headers):
                sheet.write(row, col_idx, h, header_format)
            row += 1
            for p in projects:
                total_milestones = len(p.milestone_ids)
                reached_milestones = len(p.milestone_ids.filtered(lambda m: m.is_reached))
                milestone_text = "%s / %s" % (reached_milestones, total_milestones)
                
                sheet.write(row, 0, p.project_code, data_format)
                sheet.write(row, 1, p.name, data_format)
                sheet.write(row, 2, p.user_id.name or '', data_format)
                sheet.write(row, 3, len(p.phase_ids), data_format)
                sheet.write(row, 4, milestone_text, data_format)
                sheet.write(row, 5, p.overdue_tasks_count, data_format)
                sheet.write(row, 6, p.budget_amount, num_format)
                sheet.write(row, 7, dict(p._fields['project_health'].selection).get(p.project_health, p.project_health) if p.project_health else '', data_format)
                row += 1

            row += 3
            sheet.write(row, 0, 'System: %s' % system_name, footer_format)
            sheet.write(row, 4, 'Classification: %s' % classification, footer_format)

        # ----------------------------------------------------
        # 5. Project Manager Report
        # ----------------------------------------------------
        elif self.report_type == 'pm':
            sheet = workbook.add_worksheet('Project Status Report')
            sheet.set_column('A:F', 18)

            sheet.merge_range('A2:F2', 'AHADU BANK S.C.', title_format)
            sheet.merge_range('A3:F3', 'PROJECT MANAGER EXPORT REPORT', workbook.add_format({'bold': True, 'font_size': 11, 'align': 'center'}))

            row = 6
            for p in projects:
                sheet.merge_range(row, 0, row, 5, 'Project: %s (%s)' % (p.name, p.project_code), section_format)
                row += 1
                sheet.write(row, 0, 'Planned Start:', data_format)
                sheet.write(row, 1, str(p.planned_start_date or ''), data_format)
                sheet.write(row, 2, 'Planned End:', data_format)
                sheet.write(row, 3, str(p.planned_end_date or ''), data_format)
                sheet.write(row, 4, 'Health:', data_format)
                sheet.write(row, 5, dict(p._fields['project_health'].selection).get(p.project_health, p.project_health) if p.project_health else '', data_format)
                row += 2

                # Task Summary Table
                sheet.merge_range(row, 0, row, 5, 'Task Details', section_format)
                row += 1
                headers_tasks = ['Task Number', 'Task Name', 'Assigned To', 'Deadline', 'Progress (%)', 'Status']
                for col_idx, h in enumerate(headers_tasks):
                    sheet.write(row, col_idx, h, header_format)
                row += 1
                for task in p.task_ids:
                    sheet.write(row, 0, task.task_number or '', data_format)
                    sheet.write(row, 1, task.name or '', data_format)
                    sheet.write(row, 2, ", ".join(task.user_ids.mapped('name')), data_format)
                    sheet.write(row, 3, str(task.planned_end_date or ''), data_format)
                    sheet.write(row, 4, task.completion_percentage / 100.0, pct_format)
                    sheet.write(row, 5, dict(task._fields['task_status'].selection).get(task.task_status, task.task_status) if task.task_status else '', data_format)
                    row += 1
                row += 2

            row += 1
            sheet.write(row, 0, 'System: %s' % system_name, footer_format)
            sheet.write(row, 3, 'Classification: %s' % classification, footer_format)

        # ----------------------------------------------------
        # 6. Project Team Member Report
        # ----------------------------------------------------
        elif self.report_type == 'team':
            sheet = workbook.add_worksheet('My Tasks & Deliverables')
            sheet.set_column('A:F', 18)

            sheet.merge_range('A2:F2', 'AHADU BANK S.C.', title_format)
            sheet.merge_range('A3:F3', 'PROJECT TEAM MEMBER TASKS REPORT', workbook.add_format({'bold': True, 'font_size': 11, 'align': 'center'}))
            
            row = 6
            sheet.merge_range(row, 0, row, 5, 'My Assigned Tasks and Priorities', section_format)
            row += 1
            headers = ['Task Number', 'Task Name', 'Project', 'Priority', 'Deadline', 'Status']
            for col_idx, h in enumerate(headers):
                sheet.write(row, col_idx, h, header_format)
            row += 1
            
            # Find tasks assigned to current user on these projects
            tasks = self.env['project.task'].search([
                ('project_id', 'in', projects.ids),
                ('user_ids', 'in', [self.env.user.id])
            ])
            for t in tasks:
                sheet.write(row, 0, t.task_number or '', data_format)
                sheet.write(row, 1, t.name or '', data_format)
                sheet.write(row, 2, t.project_id.name or '', data_format)
                sheet.write(row, 3, dict(t._fields['priority'].selection).get(t.priority, t.priority) if t.priority else '', data_format)
                sheet.write(row, 4, str(t.planned_end_date or ''), data_format)
                sheet.write(row, 5, dict(t._fields['task_status'].selection).get(t.task_status, t.task_status) if t.task_status else '', data_format)
                row += 1

            row += 3
            sheet.write(row, 0, 'System: %s' % system_name, footer_format)
            sheet.write(row, 3, 'Classification: %s' % classification, footer_format)

        workbook.close()
        output.seek(0)
        
        # Create an attachment in Odoo database
        xlsx_data = base64.b64encode(output.read())
        attachment = self.env['ir.attachment'].create({
            'name': 'Project_Report_%s.xlsx' % self.report_type,
            'type': 'binary',
            'datas': xlsx_data,
            'store_fname': 'Project_Report_%s.xlsx' % self.report_type,
            'mimetype': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        })
        return {
            'type': 'ir.actions.act_url',
            'url': '/web/content/%s?download=true' % attachment.id,
            'target': 'new',
        }

    def _export_pdf(self, projects):
        """Returns action to print QWeb PDF layout report."""
        self.ensure_one()
        return self.env.ref('ahadu_project_management.action_report_project_dashboard_qweb').report_action(self)


class ProjectReportQWeb(models.AbstractModel):
    _name = 'report.ahadu_project_management.rpt_project_dashboard'
    _description = 'Abstract Report for Project Dashboard QWeb template'

    @api.model
    def _get_report_values(self, docids, data=None):
        docs = self.env['project.report.wizard'].browse(docids)
        doc_projects = {}
        for doc in docs:
            doc_projects[doc.id] = doc._get_authorized_projects()
            
        return {
            'doc_ids': docids,
            'doc_model': 'project.report.wizard',
            'docs': docs,
            'doc_projects': doc_projects,
            'datetime': datetime,
        }

